import { Instagram, Facebook, Twitter } from "lucide-react";

export const socialPlatforms = [
  {
    id: "instagram-story",
    name: "Instagram Story",
    icon: Instagram,
    dimensions: { width: 1080, height: 1920 },
    aspectRatio: "9:16",
    specs: {
      maxFileSize: "30MB",
      formats: ["JPG", "PNG", "MP4"],
      safeZones: { top: 250, bottom: 250, left: 100, right: 100 },
    },
  },
  {
    id: "instagram-post",
    name: "Instagram Post",
    icon: Instagram,
    dimensions: { width: 1080, height: 1080 },
    aspectRatio: "1:1",
    specs: {
      maxFileSize: "30MB",
      formats: ["JPG", "PNG"],
      safeZones: { top: 50, bottom: 50, left: 50, right: 50 },
    },
  },
  {
    id: "facebook-post",
    name: "Facebook Post",
    icon: Facebook,
    dimensions: { width: 1200, height: 630 },
    aspectRatio: "1.91:1",
    specs: {
      maxFileSize: "8MB",
      formats: ["JPG", "PNG"],
      safeZones: { top: 40, bottom: 40, left: 40, right: 40 },
    },
  },
  {
    id: "twitter-card",
    name: "Twitter Card",
    icon: Twitter,
    dimensions: { width: 1200, height: 675 },
    aspectRatio: "16:9",
    specs: {
      maxFileSize: "5MB",
      formats: ["JPG", "PNG"],
      safeZones: { top: 30, bottom: 30, left: 30, right: 30 },
    },
  },
];

export const sampleDesigns: Record<string, any> = {
  "corporate-gala": {
    elements: [
      {
        id: "bg-corporate",
        type: "background",
        content: "",
        style: {
          background:
            "linear-gradient(135deg, #1e3a8a 0%, #3730a3 50%, #1e1b4b 100%)",
        },
        position: { x: 0, y: 0 },
        size: { width: 100, height: 100 },
        rotation: 0,
        zIndex: 0,
      },
      {
        id: "text-corp-title",
        type: "text",
        content: "Annual Innovation Summit 2024",
        style: {
          fontSize: 42,
          color: "#ffffff",
          fontFamily: "Inter, sans-serif",
        },
        position: { x: 50, y: 25, anchor: "center" },
        size: { width: 500, height: 60 },
        rotation: 0,
        zIndex: 2,
      },
      {
        id: "text-corp-date",
        type: "text",
        content: "December 15, 2024 • Grand Ballroom NYC",
        style: {
          fontSize: 20,
          color: "#e5e7eb",
          fontFamily: "Inter, sans-serif",
        },
        position: { x: 50, y: 45, anchor: "center" },
        size: { width: 400, height: 30 },
        rotation: 0,
        zIndex: 2,
      },
      {
        id: "text-corp-cta",
        type: "text",
        content: "Register Now • Limited Seats Available",
        style: {
          fontSize: 16,
          color: "#fbbf24",
          fontFamily: "Inter, sans-serif",
        },
        position: { x: 50, y: 70, anchor: "center" },
        size: { width: 350, height: 25 },
        rotation: 0,
        zIndex: 2,
      },
    ],
  },
  "birthday-celebration": {
    elements: [
      {
        id: "bg-birthday",
        type: "background",
        content: "",
        style: {
          background:
            "linear-gradient(135deg, #ec4899 0%, #f97316 50%, #eab308 100%)",
        },
        position: { x: 0, y: 0 },
        size: { width: 100, height: 100 },
        rotation: 0,
        zIndex: 0,
      },
      {
        id: "text-bday-title",
        type: "text",
        content: "Sarah's 25th Birthday Bash",
        style: {
          fontSize: 48,
          color: "#ffffff",
          fontFamily: "Inter, sans-serif",
        },
        position: { x: 50, y: 30, anchor: "center" },
        size: { width: 450, height: 70 },
        rotation: 0,
        zIndex: 2,
      },
      {
        id: "text-bday-details",
        type: "text",
        content: "Saturday, Dec 21 • 8 PM • Rooftop Terrace",
        style: {
          fontSize: 22,
          color: "#fef3c7",
          fontFamily: "Inter, sans-serif",
        },
        position: { x: 50, y: 50, anchor: "center" },
        size: { width: 400, height: 35 },
        rotation: 0,
        zIndex: 2,
      },
      {
        id: "text-bday-theme",
        type: "text",
        content: "✨ Dress Code: Glam & Glitter ✨",
        style: {
          fontSize: 18,
          color: "#fde68a",
          fontFamily: "Inter, sans-serif",
        },
        position: { x: 50, y: 70, anchor: "center" },
        size: { width: 300, height: 25 },
        rotation: 0,
        zIndex: 2,
      },
    ],
  },
  "wedding-announcement": {
    elements: [
      {
        id: "bg-wedding",
        type: "background",
        content: "",
        style: {
          background:
            "linear-gradient(135deg, #f8fafc 0%, #e2e8f0 50%, #cbd5e1 100%)",
        },
        position: { x: 0, y: 0 },
        size: { width: 100, height: 100 },
        rotation: 0,
        zIndex: 0,
      },
      {
        id: "text-wedding-names",
        type: "text",
        content: "Michael & Jennifer",
        style: {
          fontSize: 52,
          color: "#374151",
          fontFamily: "serif",
        },
        position: { x: 50, y: 25, anchor: "center" },
        size: { width: 400, height: 80 },
        rotation: 0,
        zIndex: 2,
      },
      {
        id: "text-wedding-date",
        type: "text",
        content: "June 15, 2024",
        style: {
          fontSize: 24,
          color: "#6b7280",
          fontFamily: "serif",
        },
        position: { x: 50, y: 45, anchor: "center" },
        size: { width: 200, height: 35 },
        rotation: 0,
        zIndex: 2,
      },
      {
        id: "text-wedding-venue",
        type: "text",
        content: "Garden Pavilion • Brooklyn Heights",
        style: {
          fontSize: 18,
          color: "#9ca3af",
          fontFamily: "serif",
        },
        position: { x: 50, y: 65, anchor: "center" },
        size: { width: 350, height: 25 },
        rotation: 0,
        zIndex: 2,
      },
      {
        id: "text-wedding-rsvp",
        type: "text",
        content: "RSVP by May 1st • Save the Date",
        style: {
          fontSize: 16,
          color: "#d97706",
          fontFamily: "serif",
        },
        position: { x: 50, y: 80, anchor: "center" },
        size: { width: 300, height: 20 },
        rotation: 0,
        zIndex: 2,
      },
    ],
  },
  "holiday-party": {
    elements: [
      {
        id: "bg-holiday",
        type: "background",
        content: "",
        style: {
          background:
            "linear-gradient(135deg, #059669 0%, #dc2626 50%, #059669 100%)",
        },
        position: { x: 0, y: 0 },
        size: { width: 100, height: 100 },
        rotation: 0,
        zIndex: 0,
      },
      {
        id: "text-holiday-title",
        type: "text",
        content: "Holiday Celebration 2024",
        style: {
          fontSize: 46,
          color: "#ffffff",
          fontFamily: "Inter, sans-serif",
        },
        position: { x: 50, y: 28, anchor: "center" },
        size: { width: 480, height: 70 },
        rotation: 0,
        zIndex: 2,
      },
      {
        id: "text-holiday-details",
        type: "text",
        content: "December 20 • 7 PM • Winter Wonderland Theme",
        style: {
          fontSize: 20,
          color: "#f0fdf4",
          fontFamily: "Inter, sans-serif",
        },
        position: { x: 50, y: 50, anchor: "center" },
        size: { width: 450, height: 30 },
        rotation: 0,
        zIndex: 2,
      },
      {
        id: "text-holiday-location",
        type: "text",
        content: "Metropolitan Event Center",
        style: {
          fontSize: 18,
          color: "#dcfce7",
          fontFamily: "Inter, sans-serif",
        },
        position: { x: 50, y: 68, anchor: "center" },
        size: { width: 280, height: 25 },
        rotation: 0,
        zIndex: 2,
      },
    ],
  },
  "graduation-party": {
    elements: [
      {
        id: "bg-graduation",
        type: "background",
        content: "",
        style: {
          background:
            "linear-gradient(135deg, #7c3aed 0%, #2563eb 50%, #059669 100%)",
        },
        position: { x: 0, y: 0 },
        size: { width: 100, height: 100 },
        rotation: 0,
        zIndex: 0,
      },
      {
        id: "text-grad-title",
        type: "text",
        content: "Congratulations Class of 2024!",
        style: {
          fontSize: 40,
          color: "#ffffff",
          fontFamily: "Inter, sans-serif",
        },
        position: { x: 50, y: 25, anchor: "center" },
        size: { width: 520, height: 60 },
        rotation: 0,
        zIndex: 2,
      },
      {
        id: "text-grad-name",
        type: "text",
        content: "Celebrating Alex Thompson",
        style: {
          fontSize: 26,
          color: "#e0e7ff",
          fontFamily: "Inter, sans-serif",
        },
        position: { x: 50, y: 45, anchor: "center" },
        size: { width: 380, height: 40 },
        rotation: 0,
        zIndex: 2,
      },
      {
        id: "text-grad-details",
        type: "text",
        content: "MBA Graduate • Columbia University",
        style: {
          fontSize: 18,
          color: "#c7d2fe",
          fontFamily: "Inter, sans-serif",
        },
        position: { x: 50, y: 65, anchor: "center" },
        size: { width: 320, height: 25 },
        rotation: 0,
        zIndex: 2,
      },
      {
        id: "text-grad-celebration",
        type: "text",
        content: "Join us for dinner & celebration • June 8th",
        style: {
          fontSize: 16,
          color: "#a5b4fc",
          fontFamily: "Inter, sans-serif",
        },
        position: { x: 50, y: 78, anchor: "center" },
        size: { width: 350, height: 20 },
        rotation: 0,
        zIndex: 2,
      },
    ],
  },
};

export const sampleComments = [
  {
    id: "comment-1",
    userId: "user-1",
    userName: "Emily Chen",
    userAvatar: "/api/placeholder/32/32",
    content: "Love the color scheme! Could we make the date text a bit larger?",
    position: { x: 52, y: 52 },
    timestamp: "2024-12-15T10:30:00Z",
    replies: [],
    resolved: false,
  },
  {
    id: "comment-2",
    userId: "user-2",
    userName: "Marcus Johnson",
    userAvatar: "/api/placeholder/32/32",
    content: "The gradient looks amazing! Perfect for the birthday theme.",
    position: { x: 30, y: 25 },
    timestamp: "2024-12-15T11:15:00Z",
    replies: [
      {
        id: "reply-1",
        userId: "user-3",
        userName: "Sarah Designer",
        userAvatar: "/api/placeholder/32/32",
        content: "Thanks! I was going for that festive vibe.",
        position: { x: 0, y: 0 },
        timestamp: "2024-12-15T11:20:00Z",
        replies: [],
        resolved: false,
      },
    ],
    resolved: true,
  },
];
